### ISSUE TITLE
Script for data preparation from CSVs

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/lit-gpt#329]
Example:

| Instruction | Input | Output |
| ------------ | ----- | ------- |
| What is Llama | Answer based on LLMs | Llama is a foundation model from Meta AI |

```
python scripts/prepare_csv.py --csv_path data.csv
```

**Comment by Anindyadeep** [comment]
Hey if this issue is Open, I would like to contribute to this issue. I have some questions, After running the script what kind of output is expected here (A .jsonl file? saved inside a path provided by the user with automatic train/test split)?

**Comment by aniketmaurya** [comment]
Hi @Anindyadeep, the output format should be similar to the prepare_alpaca.py script.

**Comment by Anindyadeep** [comment]
Here is what I am thinking. We can either go with one of two routes. 

1. Use the script to convert CSV to the corresponding .jsonl file, which can be further converted into LLM specific dataset
2. Or directly convert to LLM specific but in that case, we need to specify these additional arguments, which look something like this:

```bash 
python scripts/prepare_csv.py \
  --csv_path data.csv \
  --llm dolly \
  --checkpoint_dir checkpoints/stabilityai/stablelm-base-alpha-3b \
  --destination_path data/dolly-stablelm3b \
  --max_seq_length 2048
```
Now here also `--llm` can be an optinal parameter. Either we can say that the checkpoint dir should be in a certain format so that we can automatically detect the model type or we can provide the llm type to convert it to LLM specific dataset (but no such spec for checkpoint dir is required)

**Comment by Anindyadeep** [comment]
I pushed a PR #462 for this. Let me know if I need to make more changes.
