### ISSUE TITLE
Seeking Clarification on prepare_redpajama.py 

### ISSUE THREAD

**Issue by LinaZiad** [Lightning-AI/lit-gpt#500]
Hi,

Actually, I'm relatively new to the world of NLP, and I've been exploring prepare_redpajama.py.

I've noticed a configuration on Line 144 : checkpoint_dir: Path = Path("checkpoints/stabilityai/stablelm-base-alpha-3b").
I'm wondering why this particular checkpoint (3b) is being used? especially that the pretraining code is specifying a different directory (7b) : --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf/

I would like to know if it is acceptable to mix weights of different sizes, such as 3b and 7b?

looking forward to your guidance!

**Comment by rasbt** [comment]
Hi there, these are good questions. So the model you are seeing there as checkpoint_dir is just the one used be default if a user doesn't specify which one they want to use -- I suppose we defaulted to the 3B one here because it's reasonably small to run on most hardware but big enough to get some good results.

Regarding the mixing ... it's recommended to call the prepare_* scripts for each type of model you are using since the tokenizer might be different. If you use a 7B and 70B model from the same model family like Llama 2, I suppose it should be fine if you don't prepare the dataset again via this script, but I'd say it's just a good practice to reprepare it. You can save the prepared datasets to different folders so that you can reuse them later if you are switching between models. 

There's also a bit more info here if useful: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/prepare_dataset.md

**Comment by rasbt** [comment]
I think this can be closed, but let me know if you have any follow-up questions!
