### ISSUE TITLE
LoRA merging fails under quantization

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-gpt#513]
Looks like there's a bug with LoRA and quantization. This might be related to some of the recent bug reports around this.

(prints added for my convenience)
```python
        # calling merge() multiple times in a row should not merge multiple times
>       merge_lora_weights(model)

tests/test_lora.py:406: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lit_gpt/lora.py:696: in merge_lora_weights
    module.merge()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = LoRAQKVLinear(
  (lora_dropout): Dropout(p=0.1, inplace=False)
  (linear): QuantizedLinear(in_features=8, out_features=24, bias=True)
)

    def merge(self):
        """Merges the LoRA weights into the full-rank weights (W = W + delta_W)."""
    
        # Let's assume that:
        # ⚬ self.linear.weight.data: (384, 128) or (3 * embedding_size, embedding_size)
        # ⚬ self.lora_A.data: (4, 128)
        # ⚬ self.lora_B.data: (256, 2)
        if self.r > 0 and any(self.enable_lora) and not self.merged:
            delta_w = self.conv1d(
                self.lora_A.data.unsqueeze(0),  # (4, 128) -> (1, 4, 128)
                self.lora_B.data.unsqueeze(-1),  # (256, 2) -> (256, 2, 1)
            ).squeeze(
                0
            )  # (1, 4, 128) @ (256, 2, 1) -> (1, 256, 128) -> (256, 128)
            # W = W + delta_W (merge)
            x = self.zero_pad(delta_w * self.scaling)
            print(self.linear.weight.data.shape, x.shape, delta_w.shape)
>           self.linear.weight.data += x  # (256, 128) after zero_pad (384, 128)
E           RuntimeError: The size of tensor a (96) must match the size of tensor b (24) at non-singleton dimension 0

lit_gpt/lora.py:350: RuntimeError
------------------------------------ Captured stdout call ------------------------------------
torch.Size([96, 1]) torch.Size([24, 8]) torch.Size([16, 8])
```

The issue can be reproduced with ` pytest tests/test_lora.py -v -k quant -s`

The test does pass if `quantization(None)` is used. In that case, it prints `torch.Size([24, 8]) torch.Size([24, 8]) torch.Size([16, 8])`

This issue is not high priority because merging is normally done as a separate step, where the model is not quantized anymore: https://github.com/Lightning-AI/lit-gpt/blob/main/scripts/merge_lora.py

_Originally posted by @carmocca in https://github.com/Lightning-AI/lit-gpt/issues/512#issuecomment-1710035031_

**Comment by Andrei-Aksionov** [comment]
> [!NOTE]
> For posterity, I'll put my findings here as soon as I find new issues or reasons that caused them.

```text
As you can see from the log output above, the weight matrix for the `CausalSelfAttention` class
is corrupted: instead of the proper size of (24, 8) during merging it has the size of (96, 1).
```

#### 1. Weight shape corruption happens only for `LoRAQKVLinear` or also for `LoRALinear` classes?

Yes, for all quantized linear layers.
QKV matrix should have shape **(24, 8)** but in fact has **(96, 1)**.
Projection layer (right after QKV matrix) should have shape **(8, 8)** but has **(32, 1)**.
Projection layer inside MLP should have shape **(8, 32)** but has **(128, 1)**.
LM head should have shape **(512, 8)** but has **(2048, 1)**.

You can clearly see a pattern here.
And it doesn't look like `flatten`, because (8, 32).flatten() is (256), and we have (128, 1).
Actually, it looks like the size after quantization is equal to flattened original shape, divided by two, added unsqueeze(-1).

#### 1.1. What about real models?

Yes, the same. I quickly tested `Pythia-70m` and:
- lm_head: (50304, 512) --> (12877824, 1)
- QKV: (1536, 512) --> (393216, 1)
- QKV proj: (512, 512) --> (131072, 1) 

Formula is the same: flatten, divide by two, unsqueeze(-1)

#### 2. How it's possible that `merging` fails but not `forward` method? 

Have no idea 🤷.
We have:
- input `x` of shape **(2, 4, 8)**.
- `linear layer` with weight matrix of shape **(96, 1)**
- `pretrained` = linear(x) --> pretrained of shape **(2, 4, 24)**

How is that even possible, I don't have a clue.
What's more interesting is that `pretrained` of shape **(2, 4, 24)** is the correct shape :)
**(96, 1)** is the corrupted shape and the shape should be **(24, 8)**, and, of course, **(2, 4, 8)** @ **(24, 8)**.T = **(2, 4, 24)** 

#### 3. Is the weight matrix corrupted at initialization (or after forward pass)?

Neither. Initialization and forward pass don't corrupt weight matrices.
Everything happens during `fabric.setup` call.
More specifically inside this [method](https://github.com/Lightning-AI/lightning/blob/941c446a0d52ca92cc2625e30308fea6253e1458/src/lightning/fabric/fabric.py#L487).
Which is weird, because that method just uses `module.to` method, which is handled by PyTorch.
Tomorrow I'll investigate it even further.

**Comment by Andrei-Aksionov** [comment]
"Ladies and Gentlemen, we got him".

It looks like the issue is caused by the BNB [itself](https://colab.research.google.com/drive/1BsqUowCDB4N3snn6EeZG2ykvBf-Oazu1?usp=sharing).
As this is happening only after `quantization` and not `dequantization` (since forward pass works fine) I think the issue is only in the way the `shape`/`size` is reported.

Anyway, I'll check the source code more and create an issue in BNB's repo.

**Comment by Andrei-Aksionov** [comment]
I've created an issue in BNB's repo: https://github.com/TimDettmers/bitsandbytes/issues/765

**Comment by rasbt** [comment]
Thanks for handling that @Andrei-Aksionov !!

**Comment by carmocca** [comment]
I've been diving more into bitsandbytes as I work on https://github.com/Lightning-AI/lightning/pull/18655 and I think the bug is in our code and https://github.com/TimDettmers/bitsandbytes/issues/765 is working as expected.

The weights are quantized in a different shape, so the addition fails. We should either

Dequantize the weights, merge the LoRA weights and re-quantize them
or
Quantize the LoRA weights and merge them

**Comment by Andrei-Aksionov** [comment]
I wouldn't say it's a bug in our code, it's more like an unexpected behaviour.

I vote for option # 1: 
> Dequantize the weights, merge the LoRA delta and re-quantize them

In `LoRALinear` we can create a custom summation operation, which will be reused in `LoRAQKVLinear`:
https://github.com/Lightning-AI/lit-gpt/blob/c71c5c65502a5c01b15dde4bfb51d4673cdb4624/lit_gpt/lora.py#L140

The method will check dtype of the first operand and if it's quantized dtype - dequantize, do summation, quantize again.

**Comment by carmocca** [comment]
Here's how PEFT does it:https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/bnb.py#L214-L216
