### ISSUE TITLE
how to execute meta-llama/Llama-2-7b-hf

### ISSUE THREAD

**Issue by nevermet** [Lightning-AI/lit-gpt#643]
Hello

I am looking at this page: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_llama_2.md

but I am wondering what if I want to execute 'meta-llama/Llama-2-7b-hf' instead of meta-llama/Llama-2-7b-chat-hf

I've run all the commands until 'python scripts/download.py --repo_id meta-llama/Llama-2-7b-chat-hf --access_token your_hf_token' and above.

I think I can just delete 'chat-' from the commands...

However, I wonder what file I should use instead of 'chat/base.py' in the last command:
python chat/base.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-chat-hf

Thank you in advance. :)

**Comment by rasbt** [comment]
Hi there,

you can still use/try the `chat/base.py` script but the model will not be as good as the chat model since it's not been instruction tuned.

But in more general, you can use the `generate/base.py` script which is meant for general prompting. E.g.,

```bash
python generate/base.py \
  --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf \
  --prompt "your prompt here"
```

I hope this helps, and please don't hesitate to ask if you have follow-up questions.
