### ISSUE TITLE
Multi-GPU pretraining on OWT is slower, than on a single GPU

### ISSUE THREAD

**Issue by Muxas** [Lightning-AI/lit-gpt#864]
Hello!

I am trying to play with parallel pertaining on a single node with 4x Nvidia A40 GPUs. For some strange reason running `python pretrain/openwebtext_trainer.py --devices=1` reaches 3.95 it/s while `python pretrain/openwebtext_trainer.py --devices=4` reaches only 2.7 it/s. Changing number of devices to 2 or 3 gets me the same performance, as with 4 GPUs. I realize, that it could be a fault of FSDP strategy, that slows things down. However, switching to DDP makes throughput equal disregarding of number of GPUs (3.8 it/s). This is the changes to switch to DDP:
```
diff --git a/pretrain/openwebtext_trainer.py b/pretrain/openwebtext_trainer.py
index 7d7bca9..2e83b02 100644
--- a/pretrain/openwebtext_trainer.py
+++ b/pretrain/openwebtext_trainer.py
@@ -132,6 +132,7 @@ def main(devices: int = 1, precision: Optional[str] = None) -> None:
             limit_all_gathers=True,
             cpu_offload=False,
         )
+        strategy = "ddp"
     else:
         strategy = "auto"
```

Could anyone tell me how shall I launch multi-GPU pretraining to actually gain performance? I believe I am missing something, but README on pertaining states only `--devices` parameter.

**Comment by awaelchli** [comment]
Hey @Muxas 
FSDP full-sharding adds an overhead because of the extra communication. It is expected that the per-device iteration speed is lower. But for training speed you should look at the total throughput. For example, instead of iterations per second you could look at batches per second across all GPUs, which in your case will be:

Single GPU: 3.95 it/s = 3.95 batches/s
FSDP 4 GPUs: 2.7 it/s = 2.7 * 4 batches/s = 10.8 batches/s

So in that regard, you can see a speed up of about 10.8 / 3.95 = 2.73 in training time.

You  mentioned using A40G GPUs, and afaik they are normally not NVLink connected so you are probably just hitting the GPU device to device communication bottleneck. So in that sense, these numbers don't look out of the ordinary to me.

**Comment by Muxas** [comment]
Thank you for explanation. I did not get that FSDP on 4 GPUs runs 4 batches at once. At least, for a newbie it is unclear. Everything seems normal then.
