### ISSUE TITLE
Mismatch format between checkpoint saving and loading

### ISSUE THREAD

**Issue by yuzc19** [Lightning-AI/lit-gpt#879]
In the pre-training script, the checkpoint state is saved in .pth

https://github.com/Lightning-AI/lit-gpt/blob/0676f23152ee8d7084e18de19339b2422e06641c/pretrain/openwebtext.py#L186

But in the evaluation, it is expected to have lit_config.json

https://github.com/Lightning-AI/lit-gpt/blob/0676f23152ee8d7084e18de19339b2422e06641c/eval/lm_eval_harness.py#L169

I feel like a mismatch exists in the checkpointing code. Could you resolve this issue?

**Comment by carmocca** [comment]
Right now you need to manually copy the config so that it can be read from the inference scripts. The fine-tune lora tutorial mentions it: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/finetune_lora.md?plain=1#L176-L186

This will be done automatically once https://github.com/Lightning-AI/lit-gpt/issues/483 is implemented

**Comment by carmocca** [comment]
Closing in favor of that issue
