### ISSUE TITLE
Translating Configurations

### ISSUE THREAD

**Issue by UYousafzai** [Lightning-AI/lit-gpt#898]
## Title: Guidance on Translating HuggingFace Config.json for lit-gpt

**Description:**

Hello lit-gpt Team,

I am currently exploring the possibility of integrating newer models from HuggingFace into the lit-gpt framework, specifically for fine-tuning purposes. However, I have encountered some uncertainties regarding the compatibility and translation process of the config.json file from HuggingFace models to the lit-gpt setup.

**Key Points of Inquiry:**

1. **Configuration Compatibility:** Is the config.json file from HuggingFace models directly translatable to lit-gpt configuration setup? If so, are there any specific parameters or considerations that need to be taken into account during this translation?

2. **Tutorial Request:** In the case that direct translation is possible, I would greatly appreciate a brief tutorial or guidance on how to properly conduct this translation process. This tutorial would be immensely helpful not only for my current project but also for others in the community who might be interested in integrating the latest HuggingFace models into lit-gpt.

3. **Contribution Opportunity:** Assuming successful integration, I am keen on translating some of the latest model releases from HuggingFace for inclusion in lit-gpt config file, which could potentially benefit others looking to fine-tune these models using lit-gpt training code.

Any assistance or guidance you can provide on this matter would be highly appreciated. Looking forward to your response and the opportunity to contribute to the lit-gpt project.

Best regards,
Uyousafzai

**Comment by carmocca** [comment]
Hi @UYousafzai! I'm glad that you are interested in contributing.

Today the system is not automated at all. A human looks at the HF model config(s) and maps those to the `Config` arguments: https://github.com/Lightning-AI/lit-gpt/blob/main/lit_gpt/config.py#L18-L61.

There's no tutorial for this because I wouldn't know how to write it reliably. There are normally two scenarios:
1. This new HF model implementation and config is the same as that of an existing config. In this case, the conversion is very straightforward. Example: https://github.com/Lightning-AI/lit-gpt/pull/852
2. The new HF config is the same as that of an existing config but the model implementation is new (perhaps even requiring `trust_remote_code=True`). Example: https://github.com/Lightning-AI/lit-gpt/pull/801. In this case, I will often request that a model test is added (https://github.com/Lightning-AI/lit-gpt/pull/801#pullrequestreview-1773960326, https://github.com/Lightning-AI/lit-gpt/pull/804)
3. The new HF model implementations and config are new. Requires somebody familiar with the Lit-GPT model implementation to compare them, find differences, and note which things wouldn't be supported without m model changes. Example: https://github.com/Lightning-AI/lit-gpt/pull/816

(2) and (3) couldn't be reliably automated. (1) could. To do it, we would have to keep a list of supported HF model definitions (HF stores this info in https://huggingface.co/mistralai/Mixtral-8x7B-v0.1/blob/main/config.json#L2-L4) and a mapping to convert a HF model config key to Lit-GPT model config key. Then you would need to verify that the configs are the same (nothing added or removed).

Overall, automating this hasn't been worth it because the configs of type (1) don't take almost any effort to add, and the other types couldn't be automated reliably anyways.

That said, feel free to propose adding new model configs. You can find existing requests by checking the checkpoints label: https://github.com/Lightning-AI/lit-gpt/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Acheckpoints. Type (3) additions will need our approval first because we are very strict about touching the model definition.

cc @aniketmaurya who also suggested this

**Comment by UYousafzai** [comment]
Hello @carmocca,

First of all thank you for the detailed response, particularly I wasn't looking for a specific model, just had a thought that okay, how do we go on about adding different configurations, or maybe possibly automate the process, knowing this I guess I have my answer now that it won't really be possible.

I suppose I do have another question, I was interested, in creating pipelines, to be more specific I wanted to develop an entire automated process of the following steps:

1. Model Download from HF
2. Model Conversion to lit
3. Model Finetune on existing data
4. merge LoRA if LoRA used.
5. convert_lit_checkpoint
6.convert_to_gguf

now I have already created a pipeline for myself up until the point of convert_to_gguf but I started getting different sorts of errors with this, I feel like there might be quite some discord between what convert.py from the llama.cpp team requires and what the resulting models from the lit-gpt team produces and I felt like I would enjoy either to fill that gap myself or get some head start from you.

Specific Error I am receiving right now is with a pythia-1b based finetuned model --> llmware/bling-1b-0.1

### Stack Trace:

Traceback (most recent call last):
  File "./gguf-converter/convert.py", line 1470, in <module>
    main()
  File "./gguf-converter/convert.py", line 1417, in main
    params = Params.load(model_plus)
  File "./gguf-converter/convert.py", line 316, in load
    params = Params.loadHFTransformerJson(model_plus.model, hf_config_path)
  File "./gguf-converter/convert.py", line 255, in loadHFTransformerJson
    f_norm_eps        = config["rms_norm_eps"],
KeyError: 'rms_norm_eps'

upon more inspection I had to manually put the config from this repo https://huggingface.co/llmware/bling-1b-0.1/blob/main/config.json into the model folder that I was running the llama.cpp convert.py against, but its missing a few keys like the one I mentioned, now I can probably find this value from scrounging around the repo's and fill them in myself, but I feel like this is possibly because of what the llama.cpp key refers to is different to what the lit-gpt team refers to and it already exists inside the config or should've existed inside the config? is that a possibility?

again thank you for your time and if this is not the appropriate place for the discussion feel free to drop me the relevant link for the discussion page and close this issue.

Best Regards,
Uyousafzai

**Comment by Andrei-Aksionov** [comment]
Hello @UYousafzai 
Last month I created a somewhat similar pipeline: https://github.com/Lightning-AI/lit-gpt/issues/844#issuecomment-1868926079
Take a look at it. 

If you want to run that script, keep in mind that it used the outdated TinyLlama checkpoint. The current main uses the updated in #877 checkpoint.

**Comment by UYousafzai** [comment]
Hey @Andrei-Aksionov , hope you're doing well, I ended up getting in touch with you via the discord however I feel like maybe you're possibly not that active there so I am just going to drop this here as well, I wanted to possibly discuss something, is there a possibility for you to run the pipeline you mentioned in https://github.com/Lightning-AI/lit-gpt/issues/898 on the following model? https://huggingface.co/llmware/bling-1b-0.1/


My aim for asking this is to test weather after the training converting it to gguf is a problem with the config mismatch or is it something that I messed up.

Best Regards,
UYousafzai.
