### ISSUE TITLE
Standardize checkpoints in lit-gpt

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lit-gpt#923]
# Problem

Having done many experiments with lit-gpt myself, I find it cumbersome to handle checkpoints when chaining different tasks in lit-gpt. 

Example workflow:
1. I pretrain a model. This saves a checkpoint file like "step-0012345.pth" somewhere
2. I want to evaluate this checkpoint, but first I have to copy this file into a folder, rename it to "lit_model.pth", and then add all the tokenizer configs into that folder by hand.
3. I then finetune the model, which saves a "finetuned-model.pth" somewhere. Then I have to repeat step 2 to assemble a folder by hand that I can evaluate with.
4. I want to do a second finetuning, for example with DPO, on top of the previous checkpoint. 
5. I want to generate outputs or chat with the model, same problem as above.

The fact that you need to manually carry around the tokenizer and other configs is cumbersome. 

## Proposal

When we save a checkpoint in lit-gpt, no matter which script, instead of a file, we save a folder with these contents:
- lit_model.pth
- tokenizer.json
- tokenizer.model
- generation_config.json
- lit_config.json

Making the checkpoint a folder also has the benefit that any of our scripts can save additional, optional information into that folder. For example a config with hyperparameters that were used to launch the script, for reproducibility. 

I'd like to work on this if you agree.

**Comment by carmocca** [comment]
What if instead of downloading all these files (that might not be used later) and dragging them around, we add the hf hub URL to https://github.com/Lightning-AI/lit-gpt/blob/main/lit_gpt/config.py#L19 so that any file that needs a specific file can download it on demand? 

(I had the same suggestion in https://github.com/Lightning-AI/lit-gpt/issues/919)

cc @rasbt

**Comment by rasbt** [comment]
We could do that, but I wonder if that could potentially result in issues if the files in the hub get updated after someone downloaded a model and started experiments and then wants to revisit a project (weeks) later and continue with some other steps where a `config.json` is needed (this is a very rare scenario though).

**Comment by carmocca** [comment]
We can pin to a specific hub commit. In fact we probably should which would've avoided issues in the past with updates (phi was an example)

**Comment by rasbt** [comment]
Good idea. In that case I think it's a good idea.

**Comment by awaelchli** [comment]
The HF config is one thing. But what about all the other files like I described in the issue? I believe it is crucial to the ease of use in lit-gpt that these files especially the tokenizer config are readily available in your checkpoint so you can immediately evaluate/generate/chat after your finetuning run without mangling these files manually (imagine you have 10s of finetuning experiments that you all want to evaluate).

**Comment by rasbt** [comment]
Yes, I think that if you do extensive finetuning, it's potentially less error-prone to copy files from the checkpoint dir, like the tokenizer, into the target folder so the LLMs are ready to use. E.g., otherwise network issues could lead to weird bugs when things cannot be downloaded on demand. 

Also, the other issue that I am now thinking of is that some downloads require exposing your HF access token etc, which may not be desirable (right now, you only have to use it once when you or a colleague downloads the initial model).

**Comment by carmocca** [comment]
The tokenizer config I agree. Regarding other configs, I didn't want to bloat our checkpoint dir with seemingly unnecessary huggingface configs. But let's do it your way

**Comment by rasbt** [comment]
This is already completed via #984 correct?

**Comment by awaelchli** [comment]
Yes, I think we can close this. The scripts in generate/, chat/, and the convert_hf_checkpoint script will now automatically work with the checkpoint folders saved by these new scripts, because they now contain the `lit_model.pth` and other config files.

So I think mission accomplished.
